<a href="https://colab.research.google.com/github/Liam-Nova/BIT_IA_Bootcamp/blob/main/S5_C5_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Parte 1. Cargar los datos limpios

In [7]:
from google.colab import drive # Conectanonos con google drive
drive.mount('/content/drive')

import os    # la librería necesaria para la ruta de la carpeta
folder_path = '/content/drive/MyDrive/Colab Notebooks/BIT_Bootcam_IA/DataSET' # ruta de la carpeta
os.chdir(folder_path) # ruta de la carpeta

#mostar lista de archivos
os.listdir()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


['marketing_campaign.csv',
 'marketing_campaign.xlsx',
 'marketing_extract_2X_Income.xlsx',
 'linear_regression_model (1).pkl',
 'poly_regression_model (1).pkl',
 'auto-mpg.names',
 'auto-mpg.data-original',
 'auto-mpg.data',
 'Index',
 'mpg-limpios-procesados.xlsx',
 'Classification_Tests.csv',
 'heart_attack_risk_dataset.csv',
 'generated_classification_data.csv']

In [8]:
df = pd.read_csv('generated_classification_data.csv')
df.head()

Imput 1   Imput 2  Target
0  0.989532 -3.214553       1
1 -0.971155  2.464751       0
2 -1.090155  1.333711       0
3 -0.958417  1.125960       0
4  1.053018 -0.258581       1

# Parte 2. Seleccionas los conjuntos de entrenamiento y prueba

In [9]:
import sklearn
from sklearn.model_selection import train_test_split

In [10]:
X = df.drop('Target', axis=1)
Y = df['Target']

In [11]:
# X = df[['Imput 1', 'Imput 2']] hay doble corchetes
# y = df['Target'] ojo con las mayusculas

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Parte 3. Inicializarr **parámetros** (pesos) e hiperparámetros

In [13]:
weights = np.random.rand(2) # pesos de las entradas al perceptron W11 y W12
bias = np.random.rand(1)
    # np.random.rand genera un numero al azar(random) float entre el [0] y el [1]
    # el () es : (la cantidad de numeros generados en un array)

epochs = 100 # variable
#learning_rate = 0.001


In [40]:
epochs

100

In [14]:
bias

array([0.87555541])

# Parte 4. Entrenamiento del Pérceptron (.fit())

In [16]:
#n = bias + W11*Imput 1 + W12*Imput 2
# X_train['Imput 1', 'Imput 2']
n_output =bias + np.dot(X_train, weights) # np.dot multiplicacion de dos matrices
n_output.shape # .shape cuenta la cantidad de datos en el array y genera una tupla con ese valor

(160,)

In [17]:
n_output

array([ 0.55245923,  0.10208237,  1.46904035,  0.79658519,  1.77077937,
        2.89329099,  1.55048782,  0.3497141 ,  1.42157176, -1.00615874,
       -0.74611144, -0.02465387,  3.19541202,  1.23505099,  3.43286332,
        0.43364167,  1.33673538,  0.36788116,  1.14604208,  2.65946274,
        0.63352003,  1.01974647,  1.79479208,  1.82126077,  0.15435092,
        0.95906004,  0.07847635,  0.52084956,  1.09850534,  1.36045582,
       -0.22256918,  1.79032188,  0.30182647,  0.62920861,  2.15856042,
       -0.23632591,  0.02289959,  1.63811831,  0.04884966,  0.41474389,
        0.88786402, -1.13577917,  0.03906723,  1.39928633, -0.4983657 ,
       -0.16940485,  0.19797259,  1.30807597,  0.37595565,  0.09354212,
        1.49331211,  0.76357776,  2.19887563,  1.0644617 ,  0.02814527,
        0.05352657,  1.25408608,  1.58313832,  1.04496161, -0.50887018,
        1.56062278, -1.36696581,  0.45740543,  1.83103795,  2.07086458,
        1.36079264, -0.4729336 ,  2.50221077,  3.27304689,  1.37

In [15]:
X_train.head(5)

Imput 1   Imput 2
79  -0.937922  0.654473
197 -0.859060 -0.106086
38   0.925460 -0.239958
24  -1.087940  1.196182
122  1.093657  0.002867

In [18]:
def hardlim(n_output): # hardline funciones de activacion
  # Devuelve 1 si la entrada es mayor o igual a 0, y 0 en caso contrario.
  # devuelve las salidas de las predicciones

  return np.where(n_output >= 0, 1, 0)
    # np.where(condicion, valor si es verdadero o valor si es falso) se asigna a...
    # n_output >= 0 : condicion que genera un booleano que al cumplirse pasa a ser True
    # (condicion, 1, 0) True = 1 False = 0
  #return 1 if n_output >= 0 else 0

hardlim limita las predichas a 0 y 1

In [20]:
a = hardlim(n_output)
Y_predict = a

In [21]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0])

In [36]:
entrena_y = list(Y_train)

print(entrena_y)

[0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0]


In [39]:
error = Y_train - Y_predict # error = real - predicho
error_abs = abs(error).sum() # abs : valor absoluto "quita el menos y deja todos los valores positivos
      # sumatoria del error en magnitude del real - el predicho

error_abs/len(X_train) # len(X_train) calcula la cantidad de los datos de train
        # hace un promedio del error

0.34375

In [43]:
for epoch in range(epochs):
  for xi, yi in zip(X_train, Y_train):
    n_ouptput = bias + np.dot(X_train, weights)
    a = hardlim(n_output) # salida de la neurona
        # predicciones "0s y 1s"

    Y_predict = a # la salida de la neurona es la prediccion

    # error = t-a t: targets a : prediccion
    error = Y_train - Y_predict

    weigths = weights + np.dot(X_train.T, error)
    bias = bias + (error)

In [44]:
print(epoch) # ?

99
